### ISSUE TITLE
希望继续更新！

### ISSUE THREAD

**Issue by buqiyuan** [kuangshp/nestjs-mysql-api#11]
感谢作者开源，基于你的项目API，我写了个相应的前端后台管理模板练手。
https://github.com/buqiyuan/vue3-antd-admin

**Comment by kuangshp** [comment]
你好优秀

**Comment by kuangshp** [comment]
> 感谢作者开源，基于你的项目API，我写了个相应的前端后台管理模板练手。
> https://github.com/buqiyuan/vue3-antd-admin

我最近准备继续开发后端接口，做一个商城的，有兴趣来加入写vue的后台管理系统吗，有兴趣你直接扫码加我微信

**Comment by buqiyuan** [comment]
近期公司内部有很多孵化项目要做，估计没啥时间搞，后面看有需要我再找你，H5、APP、小程序、PC......都不在话下
