### ISSUE TITLE
About QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'expire_time'

### ISSUE THREAD

**Issue by mozgbrasil** [kuangshp/nestjs-mysql-api#19]
Good morning my friends

About error ocurred

I'm testing this project and the following error is being returned

    QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'expire_time'

![Captura de tela de 2022-01-24 13-01-39](https://user-images.githubusercontent.com/17202780/150818551-85b5ff4d-fd2a-408d-be60-5d167e7b1020.png)

Thanks in advance to everyone who can contribute.

**Comment by kuangshp** [comment]
> Good morning my friends
> 
> About error ocurred
> 
> I'm testing this project and the following error is being returned
> 
> ```
> QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'expire_time'
> ```
> 
> ![Captura de tela de 2022-01-24 13-01-39](https://user-images.githubusercontent.com/17202780/150818551-85b5ff4d-fd2a-408d-be60-5d167e7b1020.png)
> 
> Thanks in advance to everyone who can contribute.

Thank you for your attention. I re-pull the code and initialize the database, but there is no such problem. Please provide your operation steps and branch code, and I will test it
