### ISSUE TITLE
"404 NOT FOUND"，访问/api/v2接口error

### ISSUE THREAD

**Issue by yinfangyan** [kuangshp/nestjs-mysql-api#28]
http://www.localhost:4000/api/v2 ，访问该接口error
{"status":404,"message":"Cannot GET /api/v2/","code":1,"params":{},"path":"/api/v2/","method":"GET","timestamp":"2022/8/11"}

**Comment by kuangshp** [comment]
服务器我没部署，最近在重构，你可以跑本地代码
