### ISSUE TITLE
app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by gaoyangy** [kuangshp/nestjs-mysql-api#5]
执行npm run start:dev

$ npm run start:dev

> nest-mysql-api@0.0.1 start:dev /Users/gaoyangyang/Desktop/oaa/node/nestjs-mysql-api
> cross-env NODE_ENV=development nodemon

[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
[Nest] 80810   - 2020-05-12 23:21:02   [当前环境] development
[nodemon] app crashed - waiting for file changes before starting...

app crashed - waiting for file changes before starting...

mac
node: 10.15.1
npm: 6.4.1

**Comment by Zhouhai5520** [comment]
遇到了同样的问题，解决了吗？？？？

**Comment by kuangshp** [comment]
十一后我全部更新，后面的代码就不会有了
